// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM2BD9LXktuEwP-qAkMqs3oRYpzcUlZvE',
    appId: '1:588049312616:web:66a69ee88a5b7355c784dd',
    messagingSenderId: '588049312616',
    projectId: 'foodie-e85d8',
    authDomain: 'foodie-e85d8.firebaseapp.com',
    storageBucket: 'foodie-e85d8.firebasestorage.app',
    measurementId: 'G-KT7RZWJSWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbIEY0sNKWFT9vYcQsUk3gkhJj_XKZMcI',
    appId: '1:588049312616:android:522eb87fc6424f06c784dd',
    messagingSenderId: '588049312616',
    projectId: 'foodie-e85d8',
    storageBucket: 'foodie-e85d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd8WxPEYVcCYQZeeTLf0IVAtdemctNW4A',
    appId: '1:588049312616:ios:d9cd6392e324bd6ac784dd',
    messagingSenderId: '588049312616',
    projectId: 'foodie-e85d8',
    storageBucket: 'foodie-e85d8.firebasestorage.app',
    iosBundleId: 'com.example.foodRecipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd8WxPEYVcCYQZeeTLf0IVAtdemctNW4A',
    appId: '1:588049312616:ios:d9cd6392e324bd6ac784dd',
    messagingSenderId: '588049312616',
    projectId: 'foodie-e85d8',
    storageBucket: 'foodie-e85d8.firebasestorage.app',
    iosBundleId: 'com.example.foodRecipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBM2BD9LXktuEwP-qAkMqs3oRYpzcUlZvE',
    appId: '1:588049312616:web:ca6e18ae201f0b2cc784dd',
    messagingSenderId: '588049312616',
    projectId: 'foodie-e85d8',
    authDomain: 'foodie-e85d8.firebaseapp.com',
    storageBucket: 'foodie-e85d8.firebasestorage.app',
    measurementId: 'G-F9JBTPDYQH',
  );
}
